/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adduser;
import adddebit.adddebit;
import addsurat.addsurat;
import dashboard.*;
import e.surat.koneksi;
import e.surat.session.session;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import profil.profil;


/**
 *
 * @author fastabee
 */
public class adduser extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public adduser() {
        initComponents();
        String nipawal = session.getNip();
        nip.setText(nipawal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        nama = new javax.swing.JTextField();
        tanggal = new javax.swing.JTextField();
        nip = new javax.swing.JTextField();
        jabatan = new javax.swing.JTextField();
        jam = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelstaff = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        role = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        formnama1 = new javax.swing.JTextField();
        formnik2 = new javax.swing.JTextField();
        formnip1 = new javax.swing.JTextField();
        formemail1 = new javax.swing.JTextField();
        formjabatan1 = new javax.swing.JTextField();
        formpassword = new javax.swing.JTextField();
        formtgllahir = new com.toedter.calendar.JDateChooser();
        gender = new javax.swing.JComboBox<>();
        formlevel1 = new javax.swing.JComboBox<>();
        formalamat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_user = new rojerusan.RSTableMetro();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nama.setEditable(false);
        nama.setText("jTextField1");
        jPanel2.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));

        tanggal.setEditable(false);
        tanggal.setText("jTextField1");
        jPanel2.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 100, -1));

        nip.setEditable(false);
        nip.setText("jTextField1");
        jPanel2.add(nip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, -1));

        jabatan.setEditable(false);
        jabatan.setText("jTextField1");
        jPanel2.add(jabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, -1));

        jam.setEditable(false);
        jam.setText("jTextField1");
        jPanel2.add(jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 100, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/minihome-removebg-preview.png"))); // NOI18N
        jLabel5.setText("Dashboard");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/over.png"))); // NOI18N
        jLabel7.setText("  Overbooking");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/debitnore-removebg-preview.png"))); // NOI18N
        jLabel8.setText("DebitNote");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        labelstaff.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        labelstaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user-management-96-256.png"))); // NOI18N
        labelstaff.setText("    Staff");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelstaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelstaff, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 120, 240));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 430));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        role.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        role.setText("jLabel1");
        jPanel3.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Area");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        jLabel1.setText("BANK SUMSEL BABEL");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        photo.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/profil-removebg-preview.png"))); // NOI18N
        photo.setText("Profil");
        photo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                photoMouseClicked(evt);
            }
        });
        jPanel3.add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 90, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 1080, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Manajemen User/Staff");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(426, 426, 426)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(509, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 1070, 20));

        formnama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formnama1ActionPerformed(evt);
            }
        });
        jPanel1.add(formnama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 340, -1));

        formnik2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formnik2ActionPerformed(evt);
            }
        });
        jPanel1.add(formnik2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 340, -1));

        formnip1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formnip1ActionPerformed(evt);
            }
        });
        jPanel1.add(formnip1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 340, -1));

        formemail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formemail1ActionPerformed(evt);
            }
        });
        jPanel1.add(formemail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 340, -1));

        formjabatan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formjabatan1ActionPerformed(evt);
            }
        });
        jPanel1.add(formjabatan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 340, -1));

        formpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(formpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 340, -1));
        jPanel1.add(formtgllahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 340, -1));

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "laki-laki", "perempuan", " " }));
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 340, -1));

        formlevel1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "staff", " " }));
        jPanel1.add(formlevel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 340, -1));
        jPanel1.add(formalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 340, 40));

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, -1, -1));

        jButton2.setText("Batal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        jLabel9.setText("Nama");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        jLabel10.setText("Nik");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        jLabel11.setText("Nip");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        jLabel12.setText("Email");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        jLabel13.setText("Jabatan");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        jLabel14.setText("Password");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jLabel15.setText("Tanggal Lahir");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        jLabel16.setText("Alamat");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, 10));

        jLabel17.setText("Level");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        jLabel18.setText("Gender");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        table_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_user.setAlignmentX(0.0F);
        table_user.setAlignmentY(0.0F);
        table_user.setAltoHead(30);
        table_user.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        table_user.setFuenteFilas(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        table_user.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        table_user.setFuenteHead(new java.awt.Font("Tahoma", 1, 5)); // NOI18N
        table_user.getTableHeader().setReorderingAllowed(false);
        table_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_userMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_user);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 550, 260));

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 140, -1, -1));

        jButton4.setText("Hapus");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 140, -1, -1));

        jTextField1.setText("Cari NIP");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 140, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1210, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");

    // Timer untuk memperbarui waktu setiap detik
    Timer timer = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            // Ambil waktu sekarang
            LocalTime sekarang = LocalTime.now();
            String waktuSekarang = sekarang.format(formatter);
            
            // Set ke JTextField atau komponen lainnya
            jam.setText(waktuSekarang);
        }
    });
    timer.start();

 SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String datenow = sdf.format(new java.util.Date());
        tanggal.setText(datenow);

        
        
        
        
        String nipnya = nip.getText();
       
      
  
    
    try {
        // Koneksi ke database
        java.sql.Connection c = koneksi.getKoneksi();
        
        // Query untuk mengambil data user berdasarkan NIP
        String sql = "SELECT * FROM user WHERE nip = ?";
        java.sql.PreparedStatement ps = c.prepareStatement(sql);
        ps.setString(1, nipnya); // Masukkan parameter NIP ke query
        
        // Eksekusi query
        java.sql.ResultSet rs = ps.executeQuery();
        
        // Jika data ditemukan, tampilkan di form
        if (rs.next()) {
            String namanya = rs.getString("nama"); // Kolom 'nama'
            String emailnya = rs.getString("email"); // Kolom 'email'
            String jabatannya = rs.getString("jabatan"); // Kolom 'jabatan'
            String levelnya = rs.getString("level"); // Kolom 'jabatan'
            String Phatphoto = rs.getString("foto");
            // Tampilkan data di JForm
            nama.setText(namanya); // Misal JTextField untuk nama
            nip.setText(nipnya); // Misal JTextField untuk email
            jabatan.setText(jabatannya); // Misal JTextField untuk jabatan
            role.setText(levelnya);
             if (Phatphoto != null && !Phatphoto.isEmpty()) { 
    try {
        BufferedImage bi = ImageIO.read(new File(Phatphoto));
        Image img = bi.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        ImageIcon icon = new ImageIcon(img);
        photo.setIcon(icon); // Set ikon dari gambar
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat memuat gambar.");
        photo.setIcon(null); // Kosongkan ikon jika terjadi kesalahan
    }
} else {
    photo.setIcon(null); // Kosongkan ikon jika Phatphoto null atau kosong
}
        } else {
            // Jika data tidak ditemukan
            javax.swing.JOptionPane.showMessageDialog(this, "Data tidak ditemukan untuk NIP: " + nipnya);
        }
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
    }
    
        try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/esurat", "root", "");
    
    // Buat Statement dengan tipe ResultSet yang mendukung scroll dan concur read-only
    Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
    ResultSet set = st.executeQuery("select * from user");
    
    set.last(); // Pindah ke baris terakhir
    int row = set.getRow(); // Ambil jumlah baris
    int col = set.getMetaData().getColumnCount(); // Ambil jumlah kolom
    set.beforeFirst(); // Kembali ke awal

    String rowData[][] = new String[row][col];
    int r = 0;
    while (set.next()) {
        rowData[r][0] = String.valueOf(r+1); // Isi kolom pertama dengan nomor urut
        for (int i = 1; i < col; i++) { // Loop untuk mengambil kolom database
            rowData[r][i] = set.getString(i + 1); // Data dimulai dari kolom kedua
        }
        r++;
    }

    String[] ColumnName = {"No","nama", "Nik", "Nip", "Email", "jabatan","Password" ," Tanggal Lahir","Level" ,"Gender", "Alamat"};
     DefaultTableModel model = new DefaultTableModel(rowData, ColumnName) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Semua sel tidak dapat diedit
        }
    };

    table_user.setModel(model);
    
    
        

} catch (Exception e) {
    
}

          String rolenya = role.getText();
     if ("admin".equals(rolenya)){
         labelstaff.setVisible(true);
         }else{
           
            labelstaff.setVisible(false);
            }
    
 
     
    
    
        
        
    }//GEN-LAST:event_formWindowOpened

    private void formnama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formnama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formnama1ActionPerformed

    private void formnik2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formnik2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formnik2ActionPerformed

    private void formnip1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formnip1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formnip1ActionPerformed

    private void formemail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formemail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formemail1ActionPerformed

    private void formjabatan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formjabatan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formjabatan1ActionPerformed

    private void formpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formpasswordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
                 
       

  SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); // Format tanggal yang diinginkan
    String formattedDate = sdf.format(formtgllahir.getDate()); // Ambil dan format tanggal

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/esurat", "root", "");
        
        // Periksa apakah NIP sudah ada
        String checkQuery = "SELECT COUNT(*) FROM user WHERE nip = ?";
        PreparedStatement checkStmt = con.prepareStatement(checkQuery);
        checkStmt.setString(1, formnip1.getText());
        ResultSet rs = checkStmt.executeQuery();
        rs.next();
        
        String checkQuery2 = "SELECT COUNT(*) FROM user WHERE nik = ?";
        PreparedStatement checkStmt2 = con.prepareStatement(checkQuery2);
        checkStmt2.setString(1, formnik2.getText());
        ResultSet rs2 = checkStmt2.executeQuery();
        rs2.next();
        
        String checkQuery3 = "SELECT COUNT(*) FROM user WHERE email = ?";
        PreparedStatement checkStmt3 = con.prepareStatement(checkQuery3);
        checkStmt3.setString(1, formemail1.getText());
        ResultSet rs3 = checkStmt3.executeQuery();
        rs3.next();
        
        if (rs.getInt(1) > 0) {
            // Jika NIP sudah ada
            JOptionPane.showMessageDialog(null, "NIP sudah terdaftar, gunakan NIP yang berbeda.");
        }else if(rs2.getInt(1)>0){
         JOptionPane.showMessageDialog(null, "NIK sudah terdaftar, gunakan NIP yang berbeda.");
        }else if(rs3.getInt(1)>0){
         JOptionPane.showMessageDialog(null, "email sudah terdaftar, gunakan NIP yang berbeda.");
        }
        
        else {
            // Jika NIP belum ada, lakukan INSERT
            String insertQuery = "INSERT INTO user (nama, nik, nip, email, jabatan, password, tanggal_lahir, level, gender, alamat, foto) "
                                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement insertStmt = con.prepareStatement(insertQuery);
            insertStmt.setString(1, formnama1.getText());
            insertStmt.setString(2, formnik2.getText());
            insertStmt.setString(3, formnip1.getText());
            insertStmt.setString(4, formemail1.getText());
            insertStmt.setString(5, formjabatan1.getText());
            insertStmt.setString(6, formpassword.getText());
            insertStmt.setString(7, formattedDate);
            insertStmt.setString(8, formlevel1.getSelectedItem().toString());
            insertStmt.setString(9, gender.getSelectedItem().toString());
            insertStmt.setString(10, formalamat.getText());
            insertStmt.setString(11, "profil.jpg");
            

            int result = insertStmt.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Berhasil tambah user.");
                 formnama1.setText("");
    formnik2.setText("");
    formnip1.setText("");
    formemail1.setText("");
    formjabatan1.setText("");
    formpassword.setText("");
    formtgllahir.setDate(null);
    formlevel1.setSelectedItem("admin");
    gender.setSelectedItem("laki-laki");
    formalamat.setText("");
                formWindowOpened(null);
            } else {
                JOptionPane.showMessageDialog(null, "Gagal menambah user.");
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void table_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_userMouseClicked
         String id = table_user.getValueAt(table_user.getSelectedRow(),3).toString();
        try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/esurat", "root", "");
    Statement st = con.createStatement();
   ResultSet res = st.executeQuery("select * from user where nip='" + id + "'");
    while(res.next()){
    formnama1.setText(res.getString("nama"));
    formnik2.setText(res.getString("nik"));
    formnip1.setText(res.getString("nip"));
    formemail1.setText(res.getString("email"));
    formjabatan1.setText(res.getString("jabatan"));
    formpassword.setText(res.getString("password"));
    formtgllahir.setDate(res.getDate("tanggal_lahir"));
    formlevel1.setSelectedItem(res.getString("level"));
    gender.setSelectedItem(res.getString("gender"));
    formalamat.setText(res.getString("alamat"));
    
    }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_table_userMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          String id = table_user.getValueAt(table_user.getSelectedRow(),3).toString();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/esurat", "root", "");
    Statement st = con.createStatement();
    int r = JOptionPane.showConfirmDialog(this, "yakin hapus?");
    if(r==0){
    if(!st.execute("delete from user  where nip='" + id + "'")){
        formWindowOpened(null);
         formnama1.setText("");
    formnik2.setText("");
    formnip1.setText("");
    formemail1.setText("");
    formjabatan1.setText("");
    formpassword.setText("");
    formtgllahir.setDate(null);
    formlevel1.setSelectedItem("admin");
    gender.setSelectedItem("laki-laki");
    formalamat.setText("");
    }else{
    JOptionPane.showMessageDialog(this, "batal hapus");
    }
    }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
     SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); // Format tanggal yang diinginkan
    String formattedDate = sdf.format(formtgllahir.getDate()); 
    String id = table_user.getValueAt(table_user.getSelectedRow(), 3).toString(); // Ambil ID pengguna yang sedang diupdate

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/esurat", "root", "");

        // Validasi: Pastikan NIP, Email, atau NIK tidak duplikat pada data lain
        String checkQuery = "SELECT COUNT(*) FROM user WHERE (nip = ? OR email = ? OR nik = ?) AND nip != ?";
        PreparedStatement checkStmt = con.prepareStatement(checkQuery);
        checkStmt.setString(1, formnip1.getText());
        checkStmt.setString(2, formemail1.getText());
        checkStmt.setString(3, formnik2.getText());
        checkStmt.setString(4, id); // Pastikan data yang sama tidak diambil dari baris yang sedang diupdate
        ResultSet rs = checkStmt.executeQuery();
        rs.next();

        if (rs.getInt(1) > 0) {
            // Jika ditemukan data yang sama pada baris lain
            JOptionPane.showMessageDialog(null, "terdapat kesamaan data pada NIP atau Email atau NIK sudah digunakan oleh pengguna lain. Silakan gunakan data yang berbeda.");
        } else {
            // Jika tidak ada konflik, lanjutkan proses update
            String updateQuery = "UPDATE user SET nama = ?, nik = ?, nip = ?, email = ?, jabatan = ?, tanggal_lahir = ?, level = ?, gender = ?, alamat = ? WHERE nip = ?";
            PreparedStatement updateStmt = con.prepareStatement(updateQuery);
            updateStmt.setString(1, formnama1.getText());
            updateStmt.setString(2, formnik2.getText());
            updateStmt.setString(3, formnip1.getText());
            updateStmt.setString(4, formemail1.getText());
            updateStmt.setString(5, formjabatan1.getText());
            updateStmt.setString(6, formattedDate);
            updateStmt.setString(7, formlevel1.getSelectedItem().toString());
            updateStmt.setString(8, gender.getSelectedItem().toString());
            updateStmt.setString(9, formalamat.getText());
            updateStmt.setString(10, id);

            int result = updateStmt.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil diperbarui.");
                 formnama1.setText("");
    formnik2.setText("");
    formnip1.setText("");
    formemail1.setText("");
    formjabatan1.setText("");
    formpassword.setText("");
    formtgllahir.setDate(null);
    formlevel1.setSelectedItem("admin");
    gender.setSelectedItem("laki-laki");
    formalamat.setText("");
                formWindowOpened(null);
            } else {
                JOptionPane.showMessageDialog(null, "Gagal memperbarui data.");
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
  
            try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/esurat", "root", "");
    
    // Buat Statement dengan tipe ResultSet yang mendukung scroll dan concur read-only
    Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
    ResultSet set = st.executeQuery("select * from user where nip like '%"+jTextField1.getText()+"%' ");
    
    set.last(); // Pindah ke baris terakhir
    int row = set.getRow(); // Ambil jumlah baris
    int col = set.getMetaData().getColumnCount(); // Ambil jumlah kolom
    set.beforeFirst(); // Kembali ke awal

    String rowData[][] = new String[row][col];
    int r = 0;
    while (set.next()) {
        rowData[r][0] = String.valueOf(r+1); // Isi kolom pertama dengan nomor urut
        for (int i = 1; i < col; i++) { // Loop untuk mengambil kolom database
            rowData[r][i] = set.getString(i + 1); // Data dimulai dari kolom kedua
        }
        r++;
    }

    String[] ColumnName = {"No","nama", "Nik", "Nip", "Email", "jabatan","Password" ," Tanggal Lahir","Level" ,"Gender", "Alamat"};
   DefaultTableModel model = new DefaultTableModel(rowData, ColumnName) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Semua sel tidak dapat diedit
        }
    };

    table_user.setModel(model);
} catch (Exception e) {
    e.printStackTrace();
}
        
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        dashboard da = new dashboard();
        da.show();
        dispose();
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        addsurat su = new addsurat();
        su.show();
        dispose();
        
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        adddebit de = new adddebit();
        de.show();
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void photoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_photoMouseClicked
        // TODO add your handling code here:
        profil pro = new profil();
        pro.show();
        dispose();
    }//GEN-LAST:event_photoMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    formnama1.setText("");
    formnik2.setText("");
    formnip1.setText("");
    formemail1.setText("");
    formjabatan1.setText("");
    formpassword.setText("");
    
    
    
    formalamat.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adduser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adduser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adduser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adduser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adduser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField formalamat;
    private javax.swing.JTextField formemail1;
    private javax.swing.JTextField formjabatan1;
    private javax.swing.JComboBox<String> formlevel1;
    private javax.swing.JTextField formnama1;
    private javax.swing.JTextField formnik2;
    private javax.swing.JTextField formnip1;
    private javax.swing.JTextField formpassword;
    private com.toedter.calendar.JDateChooser formtgllahir;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jabatan;
    private javax.swing.JTextField jam;
    private javax.swing.JLabel labelstaff;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nip;
    private javax.swing.JLabel photo;
    private javax.swing.JLabel role;
    private rojerusan.RSTableMetro table_user;
    private javax.swing.JTextField tanggal;
    // End of variables declaration//GEN-END:variables
}
