/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package profil;
import adddebit.adddebit;
import addsurat.addsurat;
import adduser.*;
import dashboard.*;
import e.surat.koneksi;
import e.surat.login;
import e.surat.session.session;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fastabee
 */
public class profil extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public profil() {
        initComponents();
        String nipawal = session.getNip();
        nip.setText(nipawal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        nama = new javax.swing.JTextField();
        tanggal = new javax.swing.JTextField();
        nip = new javax.swing.JTextField();
        jabatan = new javax.swing.JTextField();
        jam = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelstaff = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        role = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        formnama = new javax.swing.JTextField();
        formnik = new javax.swing.JTextField();
        formnip = new javax.swing.JTextField();
        formemail = new javax.swing.JTextField();
        formjabatan = new javax.swing.JTextField();
        formalamat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        formpassword = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        photo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        formgender = new javax.swing.JComboBox<>();
        formlevel = new javax.swing.JComboBox<>();
        formtgllahir = new com.toedter.calendar.JDateChooser();
        iduser = new javax.swing.JLabel();
        pathnyafoto = new javax.swing.JLabel();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 2047483647));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nama.setText("jTextField1");
        jPanel2.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));

        tanggal.setText("jTextField1");
        jPanel2.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 100, -1));

        nip.setText("jTextField1");
        jPanel2.add(nip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, -1));

        jabatan.setText("jTextField1");
        jPanel2.add(jabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, -1));

        jam.setText("jTextField1");
        jPanel2.add(jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 100, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/minihome-removebg-preview.png"))); // NOI18N
        jLabel5.setText("Dashboard");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/over.png"))); // NOI18N
        jLabel7.setText("  Overbooking");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/debitnore-removebg-preview.png"))); // NOI18N
        jLabel8.setText("DebitNote");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        labelstaff.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        labelstaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user-management-96-256.png"))); // NOI18N
        labelstaff.setText("    Staff");
        labelstaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelstaffMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelstaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelstaff, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 120, 240));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 430));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        role.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        role.setText("jLabel1");
        jPanel3.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Area");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jLabel1.setText("BANK SUMSEL BABEL");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 1020, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Data Profil");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(608, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 1000, 20));

        formnama.setEditable(false);
        formnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formnamaActionPerformed(evt);
            }
        });
        jPanel1.add(formnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 340, -1));

        formnik.setEditable(false);
        formnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formnikActionPerformed(evt);
            }
        });
        jPanel1.add(formnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 340, -1));

        formnip.setEditable(false);
        formnip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formnipActionPerformed(evt);
            }
        });
        jPanel1.add(formnip, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 340, -1));

        formemail.setEditable(false);
        formemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formemailActionPerformed(evt);
            }
        });
        jPanel1.add(formemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 340, -1));

        formjabatan.setEditable(false);
        formjabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formjabatanActionPerformed(evt);
            }
        });
        jPanel1.add(formjabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 340, -1));

        formalamat.setEditable(false);
        jPanel1.add(formalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 340, 40));

        jLabel9.setText("Nama");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        jLabel10.setText("Nik");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        jLabel11.setText("Nip");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        jLabel12.setText("Email");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        jLabel13.setText("Jabatan");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        jLabel14.setText("Password");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jLabel15.setText("Tanggal Lahir");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        jLabel16.setText("Alamat");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 374, -1, -1));

        jLabel17.setText("Level");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        jLabel18.setText("Gender");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        formpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(formpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 340, -1));

        jButton1.setText("Uploud Foto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 180, -1));

        photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(photo, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 180, -1));

        jButton2.setText("Simpan ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, 110, -1));

        formgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "laki-laki", "perempuan", " " }));
        jPanel1.add(formgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 340, -1));

        formlevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "staff", " " }));
        jPanel1.add(formlevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 340, -1));
        jPanel1.add(formtgllahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 340, -1));

        iduser.setBackground(new java.awt.Color(255, 255, 255));
        iduser.setForeground(new java.awt.Color(255, 255, 255));
        iduser.setText("jLabel3");
        jPanel1.add(iduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, -1, -1));

        pathnyafoto.setBackground(new java.awt.Color(255, 255, 255));
        pathnyafoto.setForeground(new java.awt.Color(255, 255, 255));
        pathnyafoto.setText("jLabel3");
        jPanel1.add(pathnyafoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, -1, -1));

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 920, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");

    // Timer untuk memperbarui waktu setiap detik
    Timer timer = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            // Ambil waktu sekarang
            LocalTime sekarang = LocalTime.now();
            String waktuSekarang = sekarang.format(formatter);
            
            // Set ke JTextField atau komponen lainnya
            jam.setText(waktuSekarang);
        }
    });
    timer.start();

 SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String datenow = sdf.format(new java.util.Date());
        tanggal.setText(datenow);

        
        
        
        
        String nipnya = nip.getText();
       
      
  
    
    try {
        // Koneksi ke database
        java.sql.Connection c = koneksi.getKoneksi();
        
        // Query untuk mengambil data user berdasarkan NIP
        String sql = "SELECT * FROM user WHERE nip = ?";
        java.sql.PreparedStatement ps = c.prepareStatement(sql);
        ps.setString(1, nipnya); // Masukkan parameter NIP ke query
        
        // Eksekusi query
        java.sql.ResultSet rs = ps.executeQuery();
        
        // Jika data ditemukan, tampilkan di form
        if (rs.next()) {
            String namanya = rs.getString("nama"); // Kolom 'nama'
            String emailnya = rs.getString("email"); // Kolom 'email'
            String jabatannya = rs.getString("jabatan"); // Kolom 'jabatan'
            String levelnya = rs.getString("level"); // Kolom 'jabatan'
            String niknya = rs.getString("nik");
            String passwordnya = rs.getString("password");
            Date tglhirnya = rs.getDate("tanggal_lahir");
            String gendernya = rs.getString("gender");
            String alamatnya = rs.getString("alamat");
            String idnya = rs.getString("id");
            String phatphoto = rs.getString("foto");
            
            // Tampilkan data di JForm
            nama.setText(namanya); // Misal JTextField untuk nama
            nip.setText(nipnya); // Misal JTextField untuk email
            jabatan.setText(jabatannya); // Misal JTextField untuk jabatan
            role.setText(levelnya);
            formnama.setText(namanya);
            formnik.setText(niknya);
            formnip.setText(nipnya);
            formemail.setText(emailnya);
            formjabatan.setText(jabatannya);
            formpassword.setText(passwordnya);
            formtgllahir.setDate(tglhirnya);
            formlevel.setSelectedItem(levelnya);
            formgender.setSelectedItem(gendernya);
            formalamat.setText(alamatnya);
            iduser.setText(idnya);
            if (phatphoto != null && !phatphoto.isEmpty()) { 
    try {
        BufferedImage bi = ImageIO.read(new File(phatphoto));
        Image img = bi.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        ImageIcon icon = new ImageIcon(img);
        photo.setIcon(icon); // Set ikon dari gambar
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat memuat gambar.");
        photo.setIcon(null); // Kosongkan ikon jika terjadi kesalahan
    }
} else {
    photo.setIcon(null); // Kosongkan ikon jika Phatphoto null atau kosong
}

           
            
           
        } else {
            // Jika data tidak ditemukan
            javax.swing.JOptionPane.showMessageDialog(this, "Data tidak ditemukan untuk NIP: " + nipnya);
        }
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
    }
    
       

          String rolenya = role.getText();
     if ("admin".equals(rolenya)){
         labelstaff.setVisible(true);
         formnama.setEditable(true);
         formnik.setEditable(true);
         formnip.setEditable(true);
         formemail.setEditable(true);
         formjabatan.setEditable(true);
         
         formtgllahir.setEnabled(true);
         formlevel.setEnabled(true);
         formgender.setEnabled(true);
         formalamat.setEditable(true);
         }else{
           
         labelstaff.setVisible(false);
         formnik.setEditable(false);
         formnip.setEditable(false);
         formemail.setEditable(false);
         formjabatan.setEditable(false);
        
         formtgllahir.setEnabled(false);
         formlevel.setEnabled(false);
         formgender.setEnabled(false);
         formalamat.setEditable(false);
         
            
            }
    
    
    
    
        
        
    }//GEN-LAST:event_formWindowOpened

    private void formnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formnamaActionPerformed

    private void formnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formnikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formnikActionPerformed

    private void formnipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formnipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formnipActionPerformed

    private void formemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formemailActionPerformed

    private void formjabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formjabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formjabatanActionPerformed

    private void formpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formpasswordActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        dashboard dah = new dashboard();
        dah.show();
        dispose();
                
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        addsurat su = new addsurat();
        su.show();
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        adddebit deb = new adddebit();
        deb.show();
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void labelstaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelstaffMouseClicked
        // TODO add your handling code here:
        adduser adsd = new adduser();
        adsd.show();
        dispose();
    }//GEN-LAST:event_labelstaffMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       JFileChooser chooser = new JFileChooser();
       chooser.showOpenDialog(null);
       File f = chooser.getSelectedFile();
       String path = f.getAbsolutePath();
       
        try {
            BufferedImage bi = ImageIO.read(new File(path));
            Image img = bi.getScaledInstance(180, 100, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            photo.setIcon(icon);
            pathnyafoto.setText(path);
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int id = Integer.parseInt(iduser.getText().trim());

SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); // Format tanggal yang diinginkan
String formattedDate = sdf.format(formtgllahir.getDate());
String path23 = pathnyafoto.getText();
String path90 = path23.replace("\\", "\\\\");

try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/esurat", "root", "");
    Statement st = con.createStatement();

    // Cek apakah ada data dengan NIK, NIP, atau email yang sama
    String checkQuery = "SELECT COUNT(*) FROM user WHERE (nik = '" + formnik.getText() + "' OR nip = '" + formnip.getText() + "' OR email = '" + formemail.getText() + "') AND id != " + id;
    ResultSet rs = st.executeQuery(checkQuery);

    if (rs.next() && rs.getInt(1) > 0) {
        JOptionPane.showMessageDialog(null, "NIK atau NIP atau Email sudah terdaftar.");
    } else {
        // Jika tidak ada yang sama, lanjutkan dengan update
        boolean b = st.execute("UPDATE user SET nama='" + formnama.getText() + "', nik='" + formnik.getText() + "', nip='" + formnip.getText() + "', email='" + formemail.getText() + "', jabatan='" + formjabatan.getText() + "', tanggal_lahir='" + formattedDate + "', level='" + formlevel.getSelectedItem() + "', gender='" + formgender.getSelectedItem() + "', alamat='" + formalamat.getText() + "', foto='" + path90 + "' WHERE id=" + id);

        if (!b) {
            JOptionPane.showMessageDialog(null, "Berhasil Update Data");
            formWindowOpened(null);
        }
    }
} catch (Exception e) {
    e.printStackTrace();
}

        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        login loh = new login();
        loh.show();
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField formalamat;
    private javax.swing.JTextField formemail;
    private javax.swing.JComboBox<String> formgender;
    private javax.swing.JTextField formjabatan;
    private javax.swing.JComboBox<String> formlevel;
    private javax.swing.JTextField formnama;
    private javax.swing.JTextField formnik;
    private javax.swing.JTextField formnip;
    private javax.swing.JTextField formpassword;
    private com.toedter.calendar.JDateChooser formtgllahir;
    private javax.swing.JLabel iduser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jabatan;
    private javax.swing.JTextField jam;
    private javax.swing.JLabel labelstaff;
    private javax.swing.JButton logout;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nip;
    private javax.swing.JLabel pathnyafoto;
    private javax.swing.JLabel photo;
    private javax.swing.JLabel role;
    private javax.swing.JTextField tanggal;
    // End of variables declaration//GEN-END:variables
}
