/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package addsurat;
import adddebit.*;
import adduser.*;
import dashboard.*;
import e.surat.koneksi;
import e.surat.session.session;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileWriter;
import java.sql.*;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.imageio.ImageIO;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import profil.profil;
import rojerusan.RSTableMetro;

/**
 *
 * @author fastabee
 */
public class addsurat extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public addsurat() {
        initComponents();
        String nipawal = session.getNip();
        nip.setText(nipawal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        nama = new javax.swing.JTextField();
        tanggal = new javax.swing.JTextField();
        nip = new javax.swing.JTextField();
        jabatan = new javax.swing.JTextField();
        jam = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelstaff = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        role = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nomor_surat = new javax.swing.JTextField();
        nominal = new javax.swing.JTextField();
        addedby = new javax.swing.JTextField();
        tanggal_surat = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_user = new rojerusan.RSTableMetro();
        jButton3 = new javax.swing.JButton();
        hapusbtn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        keterangan = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nama.setEditable(false);
        nama.setText("jTextField1");
        jPanel2.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));

        tanggal.setEditable(false);
        tanggal.setText("jTextField1");
        jPanel2.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 100, -1));

        nip.setEditable(false);
        nip.setText("jTextField1");
        jPanel2.add(nip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, -1));

        jabatan.setEditable(false);
        jabatan.setText("jTextField1");
        jPanel2.add(jabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, -1));

        jam.setEditable(false);
        jam.setText("jTextField1");
        jPanel2.add(jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 100, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/minihome-removebg-preview.png"))); // NOI18N
        jLabel5.setText("Dashboard");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/over.png"))); // NOI18N
        jLabel7.setText("  Overbooking");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/debitnore-removebg-preview.png"))); // NOI18N
        jLabel8.setText("DebitNote");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        labelstaff.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        labelstaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user-management-96-256.png"))); // NOI18N
        labelstaff.setText("    Staff");
        labelstaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelstaffMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelstaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelstaff, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 120, 240));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 430));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        role.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        role.setText("jLabel1");
        jPanel3.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Area");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        jLabel1.setText("BANK SUMSEL BABEL");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        photo.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/profil-removebg-preview.png"))); // NOI18N
        photo.setText("Profil");
        photo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                photoMouseClicked(evt);
            }
        });
        jPanel3.add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, -10, 90, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 1020, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Manajemen Surat");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(426, 426, 426)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 1000, 20));

        nomor_surat.setEditable(false);
        nomor_surat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomor_suratActionPerformed(evt);
            }
        });
        jPanel1.add(nomor_surat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 340, -1));

        nominal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nominalActionPerformed(evt);
            }
        });
        jPanel1.add(nominal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 340, -1));

        addedby.setEditable(false);
        addedby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addedbyActionPerformed(evt);
            }
        });
        jPanel1.add(addedby, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 340, -1));
        jPanel1.add(tanggal_surat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 340, -1));

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, -1, -1));

        jButton2.setText("Batal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        jLabel9.setText("Added By");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jLabel10.setText("Tanggal");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        jLabel11.setText("Nominal");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        jLabel15.setText("Keterangan");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        table_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_user.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        table_user.setFuenteFilas(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        table_user.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        table_user.setFuenteHead(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        table_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_userMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_user);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 480, 260));

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 140, -1, -1));

        hapusbtn.setText("Hapus");
        hapusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusbtnActionPerformed(evt);
            }
        });
        jPanel1.add(hapusbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 140, -1, -1));

        jTextField1.setText("Cari Nomor Surat");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 140, 110, -1));

        keterangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keteranganActionPerformed(evt);
            }
        });
        jPanel1.add(keterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 340, 40));

        jLabel19.setText("Nomor Surat");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        jButton5.setText("Cetak Excell");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 110, 100, -1));

        jButton6.setText("Cetak PDF");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1150, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");

    // Timer untuk memperbarui waktu setiap detik
    Timer timer = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            // Ambil waktu sekarang
            LocalTime sekarang = LocalTime.now();
            String waktuSekarang = sekarang.format(formatter);
            
            // Set ke JTextField atau komponen lainnya
            jam.setText(waktuSekarang);
        }
    });
    timer.start();

 SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String datenow = sdf.format(new java.util.Date());
        tanggal.setText(datenow);

        
        
        
        
        String nipnya = nip.getText();
       
      
  
    
    try {
        // Koneksi ke database
        java.sql.Connection c = koneksi.getKoneksi();
        
        // Query untuk mengambil data user berdasarkan NIP
        String sql = "SELECT * FROM user WHERE nip = ?";
        java.sql.PreparedStatement ps = c.prepareStatement(sql);
        ps.setString(1, nipnya); // Masukkan parameter NIP ke query
        
        // Eksekusi query
        java.sql.ResultSet rs = ps.executeQuery();
        
        // Jika data ditemukan, tampilkan di form
        if (rs.next()) {
            String namanya = rs.getString("nama"); // Kolom 'nama'
            String emailnya = rs.getString("email"); // Kolom 'email'
            String jabatannya = rs.getString("jabatan"); // Kolom 'jabatan'
            String levelnya = rs.getString("level"); // Kolom 'jabatan'
            String Phatphoto = rs.getString("foto");
            // Tampilkan data di JForm
            nama.setText(namanya); // Misal JTextField untuk nama
            nip.setText(nipnya); // Misal JTextField untuk email
            jabatan.setText(jabatannya); // Misal JTextField untuk jabatan
            role.setText(levelnya);
            addedby.setText(namanya);
            if (Phatphoto != null && !Phatphoto.isEmpty()) { 
    try {
        BufferedImage bi = ImageIO.read(new File(Phatphoto));
        Image img = bi.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        ImageIcon icon = new ImageIcon(img);
        photo.setIcon(icon); // Set ikon dari gambar
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat memuat gambar.");
        photo.setIcon(null); // Kosongkan ikon jika terjadi kesalahan
    }
} else {
    photo.setIcon(null); // Kosongkan ikon jika Phatphoto null atau kosong
}
        } else {
            // Jika data tidak ditemukan
            javax.swing.JOptionPane.showMessageDialog(this, "Data tidak ditemukan untuk NIP: " + nipnya);
        }
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
    }
    
        try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/esurat", "root", "");
    
    // Buat Statement dengan tipe ResultSet yang mendukung scroll dan concur read-only
    Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
    ResultSet set = st.executeQuery("select * from surat where status = 1");
    
    set.last(); // Pindah ke baris terakhir
    int row = set.getRow(); // Ambil jumlah baris
    int col = set.getMetaData().getColumnCount(); // Ambil jumlah kolom
    set.beforeFirst(); // Kembali ke awal

    String rowData[][] = new String[row][col];
    int r = 0;
    while (set.next()) {
        rowData[r][0] = String.valueOf(r+1); // Isi kolom pertama dengan nomor urut
        for (int i = 1; i < col; i++) { // Loop untuk mengambil kolom database
            rowData[r][i] = set.getString(i + 1); // Data dimulai dari kolom kedua
        }
        r++;
    }

    String[] ColumnName = {"No","nomor Surat", "Tanggal", "Nominal","Keterangan", "Added BY"};
      DefaultTableModel model = new DefaultTableModel(rowData, ColumnName) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Semua sel tidak dapat diedit
        }
    };

    table_user.setModel(model);
    

} catch (Exception e) {
    e.printStackTrace();
}

          String rolenya = role.getText();
     if ("admin".equals(rolenya)){
         labelstaff.setVisible(true);
         hapusbtn.setVisible(true);
         }else{
           
            labelstaff.setVisible(false);
            hapusbtn.setVisible(false);
            }
     
     
     try {
    // Koneksi ke database
    java.sql.Connection c = koneksi.getKoneksi();

    // Query untuk mengambil nomor_surat terakhir
    String sql = "SELECT nomor_surat FROM surat ORDER BY CAST(SUBSTRING(nomor_surat, 3) AS UNSIGNED) DESC LIMIT 1";
    java.sql.PreparedStatement ps = c.prepareStatement(sql);

    // Eksekusi query
    java.sql.ResultSet rs = ps.executeQuery();

    String nomorSuratBaru;
    if (rs.next()) {
        // Ambil nomor terakhir
        String nomorSuratTerakhir = rs.getString("nomor_surat");

        // Ekstrak angka setelah prefix 'DB'
        int nomorTerakhir = Integer.parseInt(nomorSuratTerakhir.substring(2));

        // Tambahkan 1 untuk mendapatkan nomor berikutnya
        nomorSuratBaru = "SR" + (nomorTerakhir + 1);
    } else {
        // Jika tidak ada nomor_surat sebelumnya, mulai dari 101
        nomorSuratBaru = "SR101";
    }

    // Tampilkan nomor surat baru ke JTextField atau komponen lain
    nomor_surat.setText(nomorSuratBaru);

} catch (Exception e) {
    e.printStackTrace();
    javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
}

    
    
    
    
        
        
    }//GEN-LAST:event_formWindowOpened

    private void nomor_suratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomor_suratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomor_suratActionPerformed

    private void nominalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nominalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nominalActionPerformed

    private void addedbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addedbyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addedbyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
                 
       

SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); // Format tanggal yang diinginkan
    String formattedDate = sdf.format(tanggal_surat.getDate()); // Ambil dan format tanggal

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/esurat", "root", "");
        Statement s = con.createStatement();

        // Pengecekan apakah nomor surat sudah ada
        String checkQuery = "SELECT COUNT(*) AS count FROM surat WHERE nomor_surat = '" + nomor_surat.getText() + "'";
        ResultSet rs = s.executeQuery(checkQuery);
        rs.next(); // Pindah ke hasil pertama
        int count = rs.getInt("count");

        if (count > 0) {
            // Jika nomor surat sudah ada
            JOptionPane.showMessageDialog(null, "Nomor surat sudah ada, masukkan nomor lain.");
        } else {
            // Jika nomor surat belum ada, lakukan INSERT
            String insertQuery = "INSERT INTO surat (nomor_surat, tanggal, nominal, keterangan, addedby) " +
                                 "VALUES ('" + nomor_surat.getText() + "', '" + formattedDate + "', '" + nominal.getText() + 
                                 "', '" + keterangan.getText() + "', '" + addedby.getText() + "')";
            boolean b = s.execute(insertQuery);

            if (!b) {
                JOptionPane.showMessageDialog(null, "Berhasil tambah data");
                 nominal.setText("");
   tanggal_surat.setDate(null);
    keterangan.setText("");
                formWindowOpened(null);
            } else {
                JOptionPane.showMessageDialog(null, "Gagal tambah data");
            }
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void table_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_userMouseClicked
        String id = table_user.getValueAt(table_user.getSelectedRow(),1).toString();
        try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/esurat", "root", "");
    Statement st = con.createStatement();
    ResultSet res  = st.executeQuery("select * from  surat where  nomor_surat='" + id + "'");
    while(res.next()){
    nomor_surat.setText(res.getString("nomor_surat"));
    nominal.setText(res.getString("nominal"));
    addedby.setText(res.getString("addedby"));
    keterangan.setText(res.getString("keterangan"));
    tanggal_surat.setDate(res.getDate("tanggal"));
   
    
    }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_table_userMouseClicked

    private void hapusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusbtnActionPerformed
         SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); // Format tanggal yang diinginkan
String formattedDate = sdf.format(tanggal_surat.getDate()); 
          String id =table_user.getValueAt(table_user.getSelectedRow(),1).toString();
        try {
             Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/esurat", "root", "");
    Statement st = con.createStatement();
   boolean b= st.execute("update surat set nomor_surat='"+nomor_surat.getText()+"',nominal='"+nominal.getText()+"',tanggal='"+formattedDate+"',keterangan='"+keterangan.getText()+"',addedby='"+addedby.getText()+"', status = '0'  where  nomor_surat='" + id + "'");
        if(!b){
            nominal.setText("");
   tanggal_surat.setDate(null);
    keterangan.setText("");
            formWindowOpened(null);
        }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_hapusbtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); // Format tanggal yang diinginkan
String formattedDate = sdf.format(tanggal_surat.getDate()); 
          String id =table_user.getValueAt(table_user.getSelectedRow(),1).toString();
        try {
             Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/esurat", "root", "");
    Statement st = con.createStatement();
   boolean b= st.execute("update surat set nomor_surat='"+nomor_surat.getText()+"',nominal='"+nominal.getText()+"',tanggal='"+formattedDate+"',keterangan='"+keterangan.getText()+"',addedby='"+addedby.getText()+"'  where  nomor_surat='" + id + "'");
        if(!b){
            nominal.setText("");
   tanggal_surat.setDate(null);
    keterangan.setText("");
            formWindowOpened(null);
        }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
  
            try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/esurat", "root", "");
    
    // Buat Statement dengan tipe ResultSet yang mendukung scroll dan concur read-only
    Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
    ResultSet set = st.executeQuery("select * from surat where nomor_surat like '%"+jTextField1.getText()+"%' ");
    
    set.last(); // Pindah ke baris terakhir
    int row = set.getRow(); // Ambil jumlah baris
    int col = set.getMetaData().getColumnCount(); // Ambil jumlah kolom
    set.beforeFirst(); // Kembali ke awal

    String rowData[][] = new String[row][col];
    int r = 0;
     while (set.next()) {
        rowData[r][0] = String.valueOf(r+1); // Isi kolom pertama dengan nomor urut
        for (int i = 1; i < col; i++) { // Loop untuk mengambil kolom database
            rowData[r][i] = set.getString(i + 1); // Data dimulai dari kolom kedua
        }
        r++;
    }

    String[] ColumnName = {"NoID","nama", "Nik", "Nip", "Email"};
      DefaultTableModel model = new DefaultTableModel(rowData, ColumnName) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Semua sel tidak dapat diedit
        }
    };

    table_user.setModel(model);

} catch (Exception e) {
    e.printStackTrace();
}
        
    }//GEN-LAST:event_jTextField1KeyReleased

    private void keteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keteranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keteranganActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       MessageFormat header = new MessageFormat("Laporan Pengadaan DebitNote");
        MessageFormat footer = new MessageFormat("Terimakasih");
        try {
            PrintRequestAttributeSet set = new HashPrintRequestAttributeSet();
            set.add(OrientationRequested.PORTRAIT);
            table_user.print(RSTableMetro.PrintMode.FIT_WIDTH, header, footer, true, set, true);
            JOptionPane.showMessageDialog(null, "Transaksi berhasil");

        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
         String filename = System.getProperty("user.home") + "\\Documents\\Debit.csv";


    try {
        // Membuat FileWriter untuk menulis data ke file
        FileWriter fw = new FileWriter(filename);

        // Mendapatkan model dari JTable
        TableModel model = table_user.getModel(); // Ganti `jTable1` dengan nama JTable Anda

        // Menulis header kolom ke file CSV
        for (int col = 0; col < model.getColumnCount(); col++) {
            fw.write(model.getColumnName(col) + (col < model.getColumnCount() - 1 ? "," : ""));
        }
        fw.write("\n"); // Ganti baris setelah header

        // Menulis data baris ke file CSV
        for (int row = 0; row < model.getRowCount(); row++) {
            for (int col = 0; col < model.getColumnCount(); col++) {
                fw.write(model.getValueAt(row, col).toString() + (col < model.getColumnCount() - 1 ? "," : ""));
            }
            fw.write("\n"); // Ganti baris setelah setiap baris data
        }

        // Menutup FileWriter
        fw.close();

        // Menampilkan pesan sukses
        JOptionPane.showMessageDialog(null, "Data berhasil diekspor ke: " + filename);
    } catch (Exception e) {
        // Menampilkan pesan error jika terjadi kesalahan
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
        e.printStackTrace(); // Untuk debugging
    }
    
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void photoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_photoMouseClicked
        // TODO add your handling code here:
        profil pros = new profil();
        pros.show();
        dispose();
    }//GEN-LAST:event_photoMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       dashboard das = new dashboard();
       das.show();
       dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        adddebit deb = new adddebit();
        deb.show();
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void labelstaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelstaffMouseClicked
        // TODO add your handling code here:
        adduser ser = new adduser();
        ser.show();
        dispose();
    }//GEN-LAST:event_labelstaffMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
              
    
    
    nominal.setText("");
    keterangan.setText("");
    
    
    
    
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addsurat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addsurat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addsurat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addsurat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addsurat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addedby;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton hapusbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jabatan;
    private javax.swing.JTextField jam;
    private javax.swing.JTextField keterangan;
    private javax.swing.JLabel labelstaff;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nip;
    private javax.swing.JTextField nominal;
    private javax.swing.JTextField nomor_surat;
    private javax.swing.JLabel photo;
    private javax.swing.JLabel role;
    private rojerusan.RSTableMetro table_user;
    private javax.swing.JTextField tanggal;
    private com.toedter.calendar.JDateChooser tanggal_surat;
    // End of variables declaration//GEN-END:variables
}
